# From front camera to vechicle coordinate
header:
  frame_id: vechicle
child_frame_id: front
transform:
  rotation:
    x: -0.716810
    y: 0.000349
    z: -0.005084
    w: 0.697250
  translation:
    x: 0.046892
    y: 1.845396
    z: 1.189992
