# From left_back camera to vechicle coordinate
child_frame_id: left_back
header:
  frame_id: vechicle
transform:
  rotation:
    z: -0.580736
    y: 0.756042
    w: -0.183840
    x: 0.239477
  translation:
    y: 1.452486
    z: 1.195610
    x: -0.244302
