# From LiDAR to vechicle coordinate
header:
  frame_id: vechicle
child_frame_id: lidar
transform:
  translation:
    x: 0.010524
    y: 1.613485
    z: 1.228857
  rotation:
    x: -0.003936
    y: 0.007856
    z: 0.707845
    w: 0.706313
