# From right_back camera to vechicle coordinate
header:
  frame_id: vechicle
child_frame_id: right_back
transform:
  translation:
    x: 0.255454
    y: 1.464103
    z: 1.202321
  rotation:
    x: -0.236418
    y: 0.752298
    z: -0.589694
    w: 0.174398
